// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxvUNb7_iROpksQk9s-fQR91cBa1Mi6jA',
    appId: '1:546772850624:android:f75611ec9cc46193129a25',
    messagingSenderId: '546772850624',
    projectId: 'hospital-management-33209',
    databaseURL: 'https://hospital-management-33209-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hospital-management-33209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLsBJD_TLo_1s_PllS0rcsQ3MHIN3OsCM',
    appId: '1:546772850624:ios:c5e92977d3497ae1129a25',
    messagingSenderId: '546772850624',
    projectId: 'hospital-management-33209',
    databaseURL: 'https://hospital-management-33209-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hospital-management-33209.appspot.com',
    iosBundleId: 'com.thenone.medapp',
  );
}
